# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claveilleur < Formula
  desc "An input source switching daemon for macOS."
  homepage "https://github.com/rami3l/Claveilleur"
  version "0.1.0-TEST001"
  license "BSD-2-Clause"
  depends_on :macos

  on_macos do
    url "https://github.com/rami3l/Claveilleur/releases/download/v0.1.0-TEST001/claveilleur_darwin_universal2.tar.gz"
    sha256 "0b414b923dda24af9786fac7c8eb83f985de6455a0732f98402ae11357669f00"

    def install
      bin.install "claveilleur"
    end
  end
end
