# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claveilleur < Formula
  desc "An input source switching daemon for macOS."
  homepage "https://github.com/rami3l/Claveilleur"
  version "0.1.0-alpha5"
  license "BSD-2-Clause"
  depends_on :macos

  on_macos do
    url "https://github.com/rami3l/Claveilleur/releases/download/v0.1.0-alpha5/claveilleur_darwin_universal2.tar.gz"
    sha256 "44c18d6d6664e7997baec35946b6fd22265dd4a29775fc5b10d8ce07b05164bb"

    def install
      base_dir = "."
      if build.head? then
        system "swift", "build", "--disable-sandbox", "-c", "release"
        base_dir = `swift build --show-bin-path -c release`.strip
      end
      bin.install "#{base_dir}/claveilleur"
    end
  end

  head "https://github.com/rami3l/Claveilleur.git"
  depends_on xcode: ["14.3", :build]

  test do
    system "#{bin}/claveilleur --help"
  end
end
