# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ouverture < Formula
  desc "A default application modifier for macOS."
  homepage "https://github.com/rami3l/Ouverture"
  version "0.1.1"
  license "BSD-2-Clause"
  depends_on :macos

  on_macos do
    url "https://github.com/rami3l/Ouverture/releases/download/v0.1.1/ouverture_darwin_universal2.tar.gz"
    sha256 "ebe11e2615b5bff8dcc725f267ff30d52898936b317b30ccf3585c4ef7d86197"

    def install
      bin.install "ovt"
    end
  end

  test do
    system "#{bin}/ovt"
  end
end
