# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pacaptr < Formula
  desc "Pacman-like syntax wrapper for many package managers."
  homepage "https://github.com/rami3l/pacaptr"
  version "0.19.2"
  license "GPL-3.0-only"

  on_macos do
    url "https://github.com/rami3l/pacaptr/releases/download/v0.19.2/pacaptr-darwin-universal2.tar.gz"
    sha256 "1b384ef2f97bf9e4adc3bb593ec4bf136ef70e30e52ffdfe1bbacb6bd98ffa3c"

    def install
      bin.install "pacaptr"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rami3l/pacaptr/releases/download/v0.19.2/pacaptr-linux-arm64.tar.gz"
      sha256 "1467143ff827eb71c2d5773c4d203e180dd000857dac62c3d4e09d9deedac427"

      def install
        bin.install "pacaptr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rami3l/pacaptr/releases/download/v0.19.2/pacaptr-linux-amd64.tar.gz"
      sha256 "a50a1c1dce6308d228a7aa12fa914f5e3e700179cbaaf6012cfcfa1b46973bb9"

      def install
        bin.install "pacaptr"
      end
    end
  end

  test do
    system "#{bin}/pacaptr --help"
  end
end
