# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pacaptr < Formula
  desc "Pacman-like syntax wrapper for many package managers."
  homepage "https://github.com/rami3l/pacaptr"
  version "0.20.1"
  license "GPL-3.0-only"

  on_macos do
    url "https://github.com/rami3l/pacaptr/releases/download/v0.20.1/pacaptr-darwin-universal2.tar.gz"
    sha256 "af04e76f011d765dfb31e1cecf03c7422db6d7a27515e6a62e4653d75f49137d"

    def install
      if build.head? then
        system "cargo", "install", *std_cargo_args
      else
        bin.install "pacaptr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rami3l/pacaptr/releases/download/v0.20.1/pacaptr-linux-arm64.tar.gz"
      sha256 "cc8111b6478202bc7acd3ed70c7802ecd6b46a0009a82bbdb8602e94d9083c91"

      def install
        if build.head? then
          system "cargo", "install", *std_cargo_args
        else
          bin.install "pacaptr"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rami3l/pacaptr/releases/download/v0.20.1/pacaptr-linux-amd64.tar.gz"
      sha256 "d489345a11c8168676d6d40bc66222ddb492dd060f982a5ebe66c9b877eab998"

      def install
        if build.head? then
          system "cargo", "install", *std_cargo_args
        else
          bin.install "pacaptr"
        end
      end
    end
  end

  head "https://github.com/rami3l/pacaptr.git"

  head do
    depends_on "rust" => :build
  end

  test do
    system "#{bin}/pacaptr --help"
  end
end
