# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pacaptr < Formula
  desc "Pacman-like syntax wrapper for many package managers."
  homepage "https://github.com/rami3l/pacaptr"
  version "0.19.2"
  license "GPL-3.0-only"

  on_macos do
    url "https://github.com/rami3l/pacaptr/releases/download/v0.19.2/pacaptr-darwin-universal2.tar.gz"
    sha256 "be225ea98fcebda3844a74849a5e4cce04a80e9f039aaa27d2eb4d0bb34d5b7f"

    def install
      bin.install "pacaptr"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rami3l/pacaptr/releases/download/v0.19.2/pacaptr-linux-amd64.tar.gz"
      sha256 "5524bf5b7e7e2ff1a50fec3f49447610b029f428accd7d7b50687b9cbfdbd73d"

      def install
        bin.install "pacaptr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rami3l/pacaptr/releases/download/v0.19.2/pacaptr-linux-arm64.tar.gz"
      sha256 "ce9cf4c297ac7ef64bba51b77d7defc2712e2c04ec748b62b5122a4a469e2b29"

      def install
        bin.install "pacaptr"
      end
    end
  end

  test do
    system "#{bin}/pacaptr --help"
  end
end
