# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claveilleur < Formula
  desc "An input source switching daemon for macOS."
  homepage "https://github.com/rami3l/Claveilleur"
  version "0.1.0-alpha6"
  license "BSD-2-Clause"
  depends_on :macos

  on_macos do
    url "https://github.com/rami3l/Claveilleur/releases/download/v0.1.0-alpha6/claveilleur_darwin_universal2.tar.gz"
    sha256 "3102b9a40620806a4a000a755a0415bf011f2aa040df47c229c322fc783c5b73"

    def install
      base_dir = "."
      if build.head? then
        system "swift", "build", "--disable-sandbox", "-c", "release"
        base_dir = `swift build --show-bin-path -c release`.strip
      end
      bin.install "#{base_dir}/claveilleur"
    end
  end

  head "https://github.com/rami3l/Claveilleur.git"

  head do
    depends_on xcode: ["14.3", :build]
  end

  test do
    system "#{bin}/claveilleur --help"
  end
end
