# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ouverture < Formula
  desc "A default application modifier for macOS."
  homepage "https://github.com/rami3l/Ouverture"
  version "0.1.2"
  license "BSD-2-Clause"
  depends_on :macos

  on_macos do
    url "https://github.com/rami3l/Ouverture/releases/download/v0.1.2/ouverture_darwin_universal2.tar.gz"
    sha256 "25706cb79b28208951dc7111ca756a9215e37d939007ac8e45070805e431d9f7"

    def install
      bin.install "ovt"
    end
  end

  test do
    system "#{bin}/ovt"
  end
end
