# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pacaptr < Formula
  desc "Pacman-like syntax wrapper for many package managers."
  homepage "https://github.com/rami3l/pacaptr"
  version "0.23.2"
  license "GPL-3.0-only"

  on_macos do
    url "https://github.com/rami3l/pacaptr/releases/download/v0.23.2/pacaptr-darwin-universal2.tar.gz"
    sha256 "6788164c7980d1d9320babe9be1bb2ea7ccd72820aa05587928d0511893447cc"

    define_method(:install) do
      if build.head? then
        system "cargo", "install", *std_cargo_args
      else
        bin.install "pacaptr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rami3l/pacaptr/releases/download/v0.23.2/pacaptr-linux-amd64.tar.gz"
      sha256 "1c2f9ee938078486437694bab45b1bb79346e8ea8f6905f343de0ac4d3c94eb2"
      define_method(:install) do
        if build.head? then
          system "cargo", "install", *std_cargo_args
        else
          bin.install "pacaptr"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rami3l/pacaptr/releases/download/v0.23.2/pacaptr-linux-arm64.tar.gz"
      sha256 "0e39e3f7b1f3a3b1d1e8c198f639aeb9ca433e6d08197abb28f8eebe9fe8b67f"
      define_method(:install) do
        if build.head? then
          system "cargo", "install", *std_cargo_args
        else
          bin.install "pacaptr"
        end
      end
    end
  end

  head "https://github.com/rami3l/pacaptr.git"

  head do
    depends_on "rust" => :build
  end

  test do
    system "#{bin}/pacaptr --help"
  end
end
