# This is a basic workflow to help you get started with Actions

name: test-install

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pacaptr:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Test install
        run: |
          brew install ./pacaptr.rb
          pacaptr --help

  alire:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Test install
        run: |
          brew install ./alire.rb
          alr help | grep USAGE

  ting:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Test install
        run: |
          brew install ./ting.rb
          ting --help

  claveilleur:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test install
        run: |
          brew install ./claveilleur.rb
          claveilleur --help

  ouverture:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test install
        run: |
          brew install ./ouverture.rb
          ovt

  casks:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test install
        run: |
          brew install ./Casks/*.rb
