# This is a basic workflow to help you get started with Actions

name: test-install

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pacaptr:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Test install
        run: |
          brew install Formula/pacaptr.rb
          pacaptr --help

  pacaptr-head:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Test install
        run: |
          brew install Formula/pacaptr.rb --HEAD
          pacaptr --help

  ting:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Test install
        run: |
          brew install Formula/ting.rb
          ting --help

  claveilleur:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test install
        run: |
          brew install Formula/claveilleur.rb
          claveilleur --help

  claveilleur-head:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test install
        run: |
          brew install Formula/claveilleur.rb --HEAD
          claveilleur --help

  ouverture:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test install
        run: |
          brew install Formula/ouverture.rb
          ovt

  neovim-nightly:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test install
        run: |
          brew install Formula/neovim-nightly.rb
          nvim --help

  casks:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test install
        run: |
          # Installing ghostty currently requires org membership,
          # so we skip it in this test for now.
          rm Casks/ghostty.rb
          brew install Casks/*.rb
