# This is a basic workflow to help you get started with Actions

name: test-install

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pacaptr:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: install
        run: |
          brew install ./pacaptr.rb
          pacaptr --help

  alire:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: install
        run: |
          brew install ./alire.rb
          alr help | grep USAGE

  ting:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: install
        run: |
          brew install ./ting.rb
          ting --help

  elan-init:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: install
        run: |
          brew install ./elan-init.rb
          elan-init --help | grep 'The installer for elan'

  ouverture:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: |
          brew install ./ouverture.rb
          ovt

  casks:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: |
          brew install ./Casks/evangelion-clock.rb
          brew install ./Casks/fractal-clock.rb
          brew install ./Casks/font-dseg.rb
          brew install ./Casks/font-d2coding-all.rb
          brew install ./Casks/font-firgenerd.rb
