# This is a basic workflow to help you get started with Actions

name: test-install

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pacaptr:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          brew install ./pacaptr.rb
          pacaptr --help

  ouverture:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          brew install ./ouverture.rb
          ovt

  alire:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          brew install ./alire.rb
          alr help | grep USAGE

  ting:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          brew install ./ting.rb
          ting --help

  evangelion-clock:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: brew install ./Casks/evangelion-clock.rb

  fractal-clock:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: brew install ./Casks/fractal-clock.rb

  font-dseg:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: brew install ./Casks/font-dseg.rb
