# This is a basic workflow to help you get started with Actions

name: test-install

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  pacaptr:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Test install
        run: |
          brew install Formula/pacaptr.rb
          pacaptr --help

  pacaptr-head:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Test install
        run: |
          brew update
          brew install Formula/pacaptr.rb --HEAD
          pacaptr --help

  alire:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Test install
        run: |
          brew install Formula/alire.rb
          alr help | grep USAGE

  ting:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - if: startsWith(${{ matrix.os }}, "ubuntu")
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Test install
        run: |
          brew install Formula/ting.rb
          ting --help

  clavy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Test install
        run: |
          brew install Formula/clavy.rb
          clavy --help

  clavy-head:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Test install
        run: |
          brew update
          brew install Formula/clavy.rb --HEAD
          clavy --help

  paneru-head:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Test install
        run: |
          brew update
          brew install Formula/paneru.rb --HEAD
          paneru --help

  ouverture:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Test install
        run: |
          brew install Formula/ouverture.rb
          ovt

  neovim-nightly:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Test install
        run: |
          brew install Formula/neovim-nightly.rb
          nvim --help

  casks:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Test install
        run: |
          brew install Casks/*.rb
